baseURL = "http://localhost/"
languageCode = "en-us"
title = "desc"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
theme = "dimension"
[languages]
  [languages.ru]
    languageName = "Русский язык [ru]"
    title = "КазНИИ ГБ"
    weight = 1
    contentDir = "content/ru"
    description = "Казахский ордена \"Знак почета\" научно-исследовательский институт глазных болезней"
    [languages.ru.params]
      [languages.ru.params.navigation]
        help = "Помощь"
  [languages.kz]
    languageName = "Қазақ тілі [kz]"
    title = "ҚазКА ҒЗИ"
    weight = 2
    contentDir = "content/kz"
    description = "\"Құрмет белгісі\" орденді Қазақ көз аурулары ғылыми-зерттеу институты"
    [languages.kz.params]
      [languages.kz.params.navigation]
        help = "Көмек"
  [languages.en]
    languageName = "English [en]"
    title = "KazNII GB"
    weight = 3
    contentDir = "content/en"
    description = "Kazakhskiy ordena \"Znak pocheta\" nauchno-issledovatelskiy institut glaznykh bolezney"
    [languages.en.params]
      [languages.en.params.navigation]
        help = "Help"
[params]
  description = "description"
  [params.navigation]
    help = "Help"
